FROM node:20-slim

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./
RUN npm install
RUN npm run build
RUN mkdir -p /app/public
# Bundle app source
COPY ./dist/spa /app/public

# Expose the port
EXPOSE 8080

# Start the app
CMD ["npx", "http-server", "-o", "/app/public", "-p", "8080"]