providers:
  - id: "openai"
    name: "LM Studio"
    models:
      - id: "gemma-3-27b-it-abliterated"
        name: "Gemma3 27b"
        capabilities: ["text", "vision"]
        defaultParameters:
          temperature: 0.3
          top_p: 0.95
          max_tokens: 12000
  
  - id: "openai"
    name: "OpenAI"
    models:
      - id: "gpt-4o"
        name: "GPT-4o"
        capabilities: ["text", "vision"]
        defaultParameters:
          temperature: 0.2
          max_tokens: 1000
      
      - id: "gpt-4-turbo"
        name: "GPT-4 Turbo"
        capabilities: ["text"]
        defaultParameters:
          temperature: 0.3
          max_tokens: 2000

  - id: "google"
    name: "Google"
    models:
      - id: "gemini-2.0-flash"
        name: "Gemini 2.0 Flash"
        capabilities: ["text", "vision"]
        defaultParameters:
          temperature: 0.4
          max_tokens: 2000

  - id: "openai"
    name: "LM Studio"
    models:
      - id: "gemma3-27b"
        name: "Gemma3 27b"
        capabilities: ["text"]
        defaultParameters:
          temperature: 0.5
          top_p: 0.9
          max_tokens: 2000
      
      - id: "phi-4-reasoning"
        name: "Phi-4 Reasoning"
        capabilities: ["text"]
        defaultParameters:
          temperature: 0.4
          top_p: 0.9
          max_tokens: 2000
          
      - id: "gemma-3-27b-it-abliterated"
        name: "Gemma 3 27b Abliterated"
        capabilities: ["text", "vision"]
        defaultParameters:
          temperature: 0.3
          top_p: 0.95
          max_tokens: 12000